### ISSUE TITLE
Sobre inicio de desenvolvimento ?

### ISSUE THREAD

**Issue by daniloitj** [GabrielFerraz/10MinuteWorkout#2]
Qual ordem de execução de desenvolvimento em curto prazo ? 
Vocês falaram que tinham desenvolvido a listview, porque ela não esta aqui ? 
Vocês não postaram no blog o resumo ?
Vocês não entregaram impresso o documento de telas (ciclo 2) ?

obs: Sobre o gerenciamento de atividades (Task), uma opção é utilizar esta área para criar tarefas a serem desenvolvidas, ...

**Comment by GabrielFerraz** [comment]
O gerenciamento de atividades está sendo feita pelo trello
